---

- name: Check operating system support
  when: >
    not (false
     or (ansible_os_family    == "RedHat" and ansible_distribution_major_version == "7")
     or (ansible_os_family    == "RedHat" and ansible_distribution_major_version == "6")
     or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04")
     or (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")
    )
  fail:
    msg: "Role not supported or validated for this operation system version"

- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install sshd package on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum:
    pkg: "{{ sshd_package_name }}"
    state: present

- name: Install sshd package on Ubuntu
  when: ansible_os_family == "Debian"
  apt:
    pkg: "{{ sshd_package_name }}"
    state: present

- name: Update sshd configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^(.*?){{ item.key }}"
    state: present
    line: "{{ item.key }} {{ item.value }}"
  with_dict: "{{ sshd_dict }}"
  notify:
    -  Restart sshd
