---

- name: Check operating system support
  when: >
    not (
        (ansible_os_family == "RedHat" and ( ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7" ))
     or (ansible_distribution == "Ubuntu" and ( ansible_distribution_major_version == "14" or ansible_distribution_major_version == "16" ))
    )
  fail:
    msg: "Role not supported or validated for this operating system version"

- name: Include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"
