---
  - name: Deploy a webapp stack
    hosts: all
    become: True
    tasks:
      - name: Enable EPEL Repository on CentOS 8
        yum:
          name: epel-release
          state: present
        when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'
      - name: Enable EPEL Repository on CentOS 7
        yum:
          name: epel-release
          state: present
        when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'
      - name: Make sure universe repository is enabled
        apt_repository:
          repo: deb http://archive.ubuntu.com/ubuntu focal universe
          state: present
          update_cache: True
        when: ansible_distribution == 'Ubuntu'


      - name: Install required dependencies for Centos
        yum: name="python38" state=installed
        when: ansible_distribution == 'RedHat'

      - name: Install required dependencies for Ubuntu
        apt: name="{{ item }}" state=present update_cache=true
        with_items:
          - python
          - python-setuptools
          - python-dev
          - build-essential
          - python3-pip
        when: ansible_distribution == 'Ubuntu'

      - name: Download and Install MySQL Community Repo for Centos
        get_url:
          url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
          dest: /tmp
        command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm
        when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

      - name: Install mysql server
        yum: name=mysql-server state=installed
        when: ansible_distribution == 'RedHat'
      
      - name: Install mysql server
        apt: name=mysql-server state=installed
        when: ansible_distribution == 'Ubuntu'

      - name: Start mysql service
        service:
          name: mysql
          state: started
          enabled: yes

      - name: Create Application database
        mysql_db: name=employee_db state=present
      
      - name: Create mysql database user
        mysql_user:
          name: db_user
          password: Passw0rd
          priv: '*.*:ALL'
          state: present

      - name: Install flask python dependencies
        pip:
          name: "{{ item }}"
          state: present
          executable: pip3
        with_items:
          - flask
          - flask-mysql
      
      - name: copy app.py source code to remote server
        copy:
          src: app.py
          dest: /opt/app.py
      
      - name: start web server
        shell: FLASK_APP=app.py nohup flask run --host=0.0.0.0 &
