---
  - name: Install Packages
    hosts: all
    vars:
      root_db_password: 'Password123'
    tasks:
      - name: Install configure Mysql on Centos
        block:
          - name: Download MySQL Community Repo
            get_url:
              url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
              dest: /tmp
          - name: Install MySQL Community Repo
            ignore_errors: yes
            command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm
          - name: Install MySQL Server
            yum: name=mysql-server state=present
          - name: Install MySQL-python, this is required for the task remove anonymous user
            yum: name=MySQL-python state=present
          - name: Start MySQL Server and enable it
            service: name=mysqld state=started enabled=yes
        when: ansible_distribution == 'Centos'
        tags: centos
      
      - name: Install Configure Mysql on ubuntu
        block:
          - name: Install MySQL Server
            apt: name="{{ item }}" state=latest
            with_items:
              - mysql-server
              - mysql-client
              - python-mysqldb
              - python3-pip
              - python-setuptools
          - name: Start MySQL Server and enable it
            service: name=mysql state=started enabled=yes
        when: ansible_distribution == 'Ubuntu'
        tags: ubuntu

      - name: Remove Test database if it exist.
        mysql_db: name=test state=absent
        ignore_errors: yes
      - name: Remove All Anonymous User Accounts
        mysql_user: name=” host_all=yes state=absent
        ignore_errors: yes

      - name: Output ansible_hostname
        debug: msg=”Hostname is {{ansible_hostname}}”
      - name: Change root password
        mysql_user: name=root host={{item}} password={{root_db_password}}
        with_items:
        - “{{ansible_hostname}}”
        - 127.0.0.1
        - ::1
        - localhost
        ignore_errors: yes

      - name: Create mysql database user
        mysql_user:
          name: db_user
          login_user: root
          login_password: "{{root_db_password}}"
          password: "{{root_db_password}}"
          priv: '*.*:ALL'
          state: present
        ignore_errors: yes

      - name: Create Application database
        mysql_db:
          login_user: db_user
          login_password: "{{root_db_password}}"
          name: employee_db
          state: present

      - name: Install flask python dependencies
        pip:
          name: "{{ item }}"
          state: present
          executable: pip3
        with_items:
          - flask
          - flask-mysql
          
      - name: copy app.py source code to remote server
        copy:
          src: app.py
          dest: /opt/app.py

      - name: start web server
        shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
      
