# In this example we going to pass the register variable value rc code as an input to next task to perform a condition check.
---
  - hosts: all
    gather_facts: no
    tasks: 
      - name: echoing text
        command: "echo Hello There"
        register: echo_output
      
      - name: Do a condition check if echo_output succeeds or fails
        command: "echo script ran well"
        register: "out_message"
      - debug:
          msg: "{{ out_message.stdout }}"
        when: echo_output.rc == 0

